# Default configuration for RailsSpotlight
PROJECT_NAME: <%=Rails.application.class.respond_to?(:module_parent_name) ? Rails.application.class.module_parent_name : Rails.application.class.parent_name%>
SOURCE_PATH: <%=Rails.root%>
STORAGE_PATH: <%=Rails.root.join('tmp', 'data', 'rails_spotlight')%>
STORAGE_POOL_SIZE: 10000
LOGGER: <%=Logger.new(Rails.root.join('log', 'rails_spotlight.log'))%>
MIDDLEWARE_SKIPPED_PATHS: []
NOT_ENCODABLE_EVENT_VALUES:
SKIP_RENDERED_IVARS: []
# Rest of the configuration is required for ActionCable. It will be disabled automatically in when ActionCable is not available.
# LIVE_CONSOLE_ENABLED from version 0.2.3 do not require ActionCable to be enabled.
LIVE_CONSOLE_ENABLED: true
# Experimental feature.
REQUEST_COMPLETED_BROADCAST_ENABLED: true
AUTO_MOUNT_ACTION_CABLE: true
ACTION_CABLE_MOUNT_PATH: /cable
BLOCK_EDITING_FILES: true
BLOCK_EDITING_FILES_OUTSIDE_OF_THE_PROJECT: true
